export const HerokuURL = 'https://sangat-arrival-backend-nonprod.herokuapp.com/';

export const LOCAL_DATE_FORMAT = "YYYY-MM-DD";



export const AirlineNames = [
    "AEROFLOT", 
    "AERONOMAD",
    "AIR ALGERIA", 
    "AIR ARABIA",
    "AIR ARABIA ABU DHABI", 
    "AIR ASTANA",
    "AIR AUSTRAL",
    "AIR CANADA",
    "AIR CHINA",
    "AIR FRANCE",
    "AIR INDIA",
    "AIR INDIA EXPRESS",
    "AIR MANAS", 
    "AIR MAURITIUS",
    "AIRASIA INDIA",
    "AIRASIA X",
    "ANA",
    "ALLIANCE AIR",
    "AMERICAN AIRLINES", 
    "ARIANA AFGHAN AIRLINES",
    "ASIANA AIRLINES",
    "AVIANCA",
    "AZAL AZERBAIJAN AIRLINES",
    "BHUTAN AIRLINES",
    "BIMAN BANGLADESH AIRLINES",
    "BRITISH AIRWAYS",
    "CATHAY PACIFIC",
    "CHINA AIRLINES",
    "CHINA SOUTHERN AIRLINES",
    "DELTA AIR LINES",
    "DRUKAIR",
    "EGYPTAIR",
    "EMIRATES",
    "ETHOPIAN AIRLINES",
    "ETIHAD AIRWAYS",
    "EUROATLANTIC AIRWAYS",
    "FIJI AIRWAYS",
    "FINNAIR",
    "FLEX FLIGHT",
    "FLYBIG",
    "FLY DUBAI",
    "FLYNAS",
    "GARUDA INDONESIA",
    "GO FIRST",
    "GULF AIR",
    "HONG KONG AIRLINES",
    "IBERIA",
    "INDIGO",
    "IRAQI AIRLINES",
    "ITA AIRWAYS",
    "JAL AIRLINES",
    "JAZEERA AIRWAYS",
    "KAM AIR",
    "KENYA AIRWAYS",
    "KLM",
    "KOREAN AIR",
    "KUWAIT AIRWAYS",
    "LOT POLISH AIRLINES",
    "LUFTHANSA",
    "MAHAN AIR",
    "MALAYSIA AIRLINES",
    "MALDIVIAN",
    "MALINDO AIR",
    "MIAT- MONGOLIAN AIRLINES",
    "MYANMAR AIRWAYS",
    "NEPAL AIRLINES",
    "OMAN AIR",
    "QANTAS",
    "QATAR AIRWAYS",
    "SAS",
    "SUADI",
    "SHANDONG AIRLINES",
    "SINGAPORE AIRLINES",
    "SOMAN AIR",
    "SPICE JET",
    "SRILANKAN AIRLINES",
    "SWISS",
    "TAP AIR PORTUGAL",
    "THAI AIRWAYS",
    "THAI LION AIR",
    "TURKISH AIRLINES",
    "UKRAINE AIRLINES",
    "UNITED AIRLINES",
    "UZBEKISTAN AIRWAYS"
];

export const countries = [
    "AUSTRALIA",
    "BOLIVIA",
    "CANADA",
    "FRANCE",
    "GERMANY",
    "INDIA",
    "ITALY",
    "MALAYSIA",
    "NEW ZEALAND",
    "UK",
    "USA",
]

export const asthaans = [
   "SURREY",
   "EDMONTON",
   "CALGARY",
   "TORONTO",
   "FRANCE",
   "ITALY",
   "MALAYSIA",
   "AUSTRALIA",
   "NEW ZEALAND",
   "FRESNO",
   "INDIANA",
   "NEW YORK",
   "MICHIGAN",
   "WALSALL",
   "GERMANY"
]
export const USA_STATES = [
    "ALABAMA",
    "ALASKA",
    "ARKANSAS",
    "ARIZONA",
    "CALIFORNIA",
    "COLORADO",
    "CONNECTICUT",
    "DELAWARE",
    "FLORIDA",
    "GEORGIA",
    "HAWAII",
    "IDAHO",
    "ILLINOIS",
    "INDIANA",
    "IOWA",
    "KANSAS",
    "KENTUCY",
    "LOUISANA",
    "MAINE",
    "MARYLAND",
    "MASSACHUSETTS",
    "MICHIGAN",
    "MINNESOTA",
    "MISSISSPPI",
    "MISSOURI",
    "MONTANA",
    "NEBRASKA",
    "NEVADA",
    "NEW HAMISHIRE",
    "NEW JERSEY",
    "NEW MEXICO",
    "NEW YORK",
    "NORTH CAROLINA",
    "NORTH DAKOTA",
    "OHIO",
    "OKLAHOMA",
    "OREGON",
    "PENNSYLVANIA",
    "RHODE ISLAND",
    "SOUTH CAROLINA",
    "SOUTH DAKOTA",
    "TENNESSEE",
    "TEXAS",
    "UTAH",
    "VERMONT",
    "VIRGINIA",
    "WASHINGTON",
    "WASHINGTON DC",
    "WEST VIRGINIA",
    "WISCONSIN",
    "WYOMING"
]

export const CANADA_PROVINCES = [
    "BRITISH COLUMBIA",
    "ALBERTA",
    "YUKON",
    "MANITOBA",
    "ONTARIO",
    "NORTHWEST TERRITORIES",
    "SASKATCHEWAN",
    "NEW BRUNSWICK",
    "NEWFOUNDLAND",
    "LABRADOR",
    "NOVA SCOTIA",
    "PRINCE EDWARD ISLAND"
]

export const INDIA_AIRPORT_LIST = [
    "AMRITSAR",
    "DELHI"
]

export const OVERIDE_USER_LIST = [
    "sandeep",
    "amanjodh",
    "Manjodh",
]