export const HerokuURL = 'https://guarded-gorge-38921.herokuapp.com/';



export const AirportNames = [
    "Aeroflot", 
    "Aeronomad",
    "Air Algeria", 
    "Air Arabia",
    "Air Arabia Abu Dhabi", 
    "Air Astana",
    "Air Austral",
    "Air Canada",
    "Air China",
    "Air France",
    "Air India",
    "Air India Express",
    "Air Manas", 
    "Air Mauritius",
    "AirAsia India",
    "AirAsia X",
    "ANA",
    "Alliance Air",
    "American Airlines", 
    "Ariana Afghan Airlines",
    "Asiana Airlines",
    "Avianca",
    "Azal Azerbaijan Airlines",
    "Bhutan Airlines",
    "Biman Bangladesh Airlines",
    "British Airways",
    "Cathay Pacific",
    "China Airlines",
    "China Southern Airlines",
    "Delta Air Lines",
    "Drukair",
    "Egyptair",
    "Emirates",
    "Ethopian Airlines",
    "Etihad Airways",
    "Euroatlantic airways",
    "Fiji Airways",
    "Finnair",
    "Flex Flight",
    "FlyBig",
    "Fly Dubai",
    "Flynas",
    "Garuda Indonesia",
    "Go First",
    "Gulf Air",
    "Hong Kong Airlines",
    "Iberia",
    "Indigo",
    "Iraqi Airlines",
    "ITA Airways",
    "JAL airlines",
    "Jazeera Airways",
    "Kam Air",
    "Kenya Airways",
    "KLM",
    "Korean Air",
    "Kuwait Airways",
    "LOT Polish Airlines",
    "Lufthansa",
    "Mahan Air",
    "Malaysia Airlines",
    "Maldivian",
    "Malindo Air",
    "Miat- Mongolian Airlines",
    "Myanmar Airways",
    "Nepal Airlines",
    "Oman Air",
    "Qantas",
    "Qatar Airways",
    "SAS",
    "Suadi",
    "Shandong Airlines",
    "Singapore Airlines",
    "Soman Air",
    "Spice Jet",
    "Srilankan Airlines",
    "Swiss",
    "Tap Air Portugal",
    "Thai Airways",
    "Thai Lion Air",
    "Turkish Airlines",
    "Ukraine Airlines",
    "United Airlines",
    "Uzbekistan Airways"

];

export const countries = [
    "Bolivia",
    "Canada",
    "UK",
    "Germany",
    "France",
    "Italy",
    "Malaysia",
    "Australia",
    "New Zealand",
    "India",
    "Other",
]